"""
Orchestrator - runs Stage 0 -> Stage A -> Stage B and assembles the manifest.
This is the single entry point the UI (or any other caller) should use.
"""
from .schema_resolution import resolve_schema, detect_conventions
from .cleaning import run_stage_a
from .shaping import run_stage_b, TASK_BUILDERS
from .splitting import compute_time_split
from .query_engine import build_sqlite_db
from .nl_to_sql import generate_nl_sql_examples
from .summarization_v2 import generate_summarization_examples
from .manifest import Manifest
from datetime import datetime

# Sentinel used when the user explicitly chooses "no entity column available -
# auto-index rows" instead of picking a real column.
AUTO_INDEX_ENTITY_ID = "__AUTO_INDEX_ENTITY_ID__"


def run_pipeline(raw_df, source_name: str, task_types, manual_overrides=None,
                  train_frac: float = 0.70, val_frac: float = 0.15,
                  progress_callback=None, extra_context_cols=None):
    """
    raw_df: arbitrary raw transaction DataFrame
    source_name: label for this data source, used in the manifest
    task_types: list of task type strings to shape output for
                (subset of TASK_BUILDERS keys)
    manual_overrides: optional {canonical_field: source_column} - used when
                       automated schema resolution could not confidently map
                       a required field and the user was asked to pick one.
                       For entity_id specifically, the value may be
                       AUTO_INDEX_ENTITY_ID to request row-index generation
                       instead of pointing to a real column.
    train_frac, val_frac: fraction of chronologically-ordered rows assigned
                       to train/val; the remainder becomes test. Split is
                       time-based (never random) - see splitting.py.
    progress_callback: optional callable(label: str, fraction: float 0-1),
                       invoked as each stage completes - lets a UI show a
                       progress bar without the orchestrator depending on
                       any particular UI framework.
    extra_context_cols: optional list of quarantined RAW column names the
                       user explicitly chose to carry through into shaped
                       output as extra context, even though they don't fit
                       the canonical schema. These are NOT PII-hashed like
                       entity_id/counterparty - the caller (UI) is
                       responsible for warning before letting a user select
                       a column that might contain sensitive raw values.

    Returns: dict with keys:
        mapping_report, quarantined_columns, clean_df, cleaning_stats,
        split_stats, shaped_outputs (dict task_type -> examples list), manifest
    """
    def _progress(label, frac):
        if progress_callback:
            progress_callback(label, frac)

    manual_overrides = manual_overrides or {}
    manifest = Manifest(source_name)
    raw_df = raw_df.copy()

    # Stage 0
    _progress("Resolving schema (Stage 0)...", 0.05)
    mapping_report, column_map, quarantined_columns, direction_col = resolve_schema(raw_df)

    # Apply any user-provided mappings for fields automation couldn't resolve
    for field, src_col in manual_overrides.items():
        if not src_col:
            continue

        if field == "entity_id" and src_col == AUTO_INDEX_ENTITY_ID:
            idx_col = "__auto_entity_id__"
            raw_df[idx_col] = [f"ROW_{i:06d}" for i in range(len(raw_df))]
            column_map[idx_col] = "entity_id"
            mapping_report.append({
                "source_column": idx_col, "canonical_field": "entity_id",
                "confidence": 1.0, "method": "auto_row_index", "status": "auto_generated",
            })
            manifest.warn(
                "No entity/account identifier column was available for 'entity_id'; "
                "it was auto-generated by row index (each row = a distinct entity). "
                "This means every transaction is treated as independent - rolling "
                "features, time-since-last-transaction, and multi-transaction context "
                "windows (fraud/summarization/general-behavioral tasks) will be "
                "effectively length-1 and provide little signal. Categorization is "
                "unaffected since it doesn't depend on entity grouping. Provide a real "
                "account/customer identifier column for production use of the other tasks."
            )
            continue

        # An override replaces whichever column previously held this
        # canonical field - without this, both the old and new source
        # columns end up mapped to the same field, producing a duplicate
        # column name that breaks the SQLite export (and is wrong anyway:
        # a canonical field can only come from one source column).
        superseded_cols = [c for c, f in column_map.items() if f == field and c != src_col]
        for old_col in superseded_cols:
            del column_map[old_col]
            mapping_report = [m for m in mapping_report if m["source_column"] != old_col]
            quarantined_columns.append(old_col)
            mapping_report.append({
                "source_column": old_col, "canonical_field": None,
                "confidence": 0.0, "method": "superseded_by_override", "status": "quarantined",
            })

        column_map[src_col] = field
        quarantined_columns = [q for q in quarantined_columns if q != src_col]
        mapping_report = [m for m in mapping_report if m["source_column"] != src_col]
        mapping_report.append({
            "source_column": src_col, "canonical_field": field,
            "confidence": 1.0, "method": "user_provided", "status": "manual_override",
        })

    _progress("Detecting unit/date conventions...", 0.15)
    amount_assumptions = detect_conventions(raw_df, column_map, direction_col)
    manifest.set_schema_resolution(mapping_report, quarantined_columns)
    for m in mapping_report:
        if m.get("note"):
            manifest.warn(f"[{m['source_column']}] {m['note']}")
    for a in amount_assumptions:
        manifest.warn(f"[{a['field']}] {a['assumption']} (confidence: {a['confidence']})")
    manifest.data["schema_resolution"]["convention_assumptions"] = [
        {k: v for k, v in a.items() if not k.startswith("_")} for a in amount_assumptions
    ]

    missing_required = {"entity_id", "timestamp", "amount"} - set(column_map.values())
    if missing_required:
        manifest.warn(f"Required canonical field(s) could not be mapped: {sorted(missing_required)}")
        return {
            "mapping_report": mapping_report,
            "quarantined_columns": quarantined_columns,
            "clean_df": None,
            "cleaning_stats": None,
            "split_stats": None,
            "shaped_outputs": {},
            "manifest": manifest,
            "fatal_error": f"Missing required field(s): {sorted(missing_required)}",
        }

    # Stage A
    _progress("Cleaning & validating (Stage A)...", 0.30)
    clean_df, cleaning_stats = run_stage_a(raw_df, column_map, direction_col, amount_assumptions,
                                            extra_context_cols=extra_context_cols,
                                            warn_callback=manifest.warn)
    manifest.set_cleaning(cleaning_stats)
    if extra_context_cols:
        manifest.warn(
            f"Extra context columns carried through unhashed (opt-in, user-selected): "
            f"{extra_context_cols}. These were quarantined by schema resolution and are "
            f"NOT covered by the pipeline's PII-hashing or validation - review their "
            f"content before using output that includes them."
        )

    # Time-based split (never random - see splitting.py)
    _progress("Computing time-based train/val/test split...", 0.45)
    split_stats = None
    if len(clean_df) > 0:
        clean_df, split_stats = compute_time_split(clean_df, train_frac=train_frac, val_frac=val_frac)
        manifest.data["splitting"] = split_stats

    # Stage B
    shaped_outputs = {}
    n_tasks = max(len(task_types), 1)

    # query_sql and the new fact-grounded summarization both need a real
    # queryable database and the split cutoffs (as datetimes) to label
    # generated examples correctly - build these once, lazily, only if needed
    needs_query_engine = any(t in ("query_sql", "spend_summarization") for t in task_types)
    conn = None
    split_cutoffs = None
    if needs_query_engine and split_stats:
        conn = build_sqlite_db(clean_df, warn_callback=manifest.warn)
        split_cutoffs = (
            datetime.fromisoformat(split_stats["train_cutoff"]),
            datetime.fromisoformat(split_stats["val_cutoff"]),
        )

    for i, task_type in enumerate(task_types):
        _progress(f"Shaping output for task: {task_type}...", 0.5 + (i / n_tasks) * 0.45)

        if task_type == "query_sql":
            examples = generate_nl_sql_examples(clean_df, conn, split_cutoffs)
            stats = {
                "task_type": "query_sql",
                "example_count": len(examples),
                "note": "Every SQL query was executed against the real cleaned data and "
                        "validated before being kept - none are guessed or unverified.",
            }
        elif task_type == "spend_summarization":
            examples = generate_summarization_examples(clean_df, conn, split_cutoffs)
            stats = {
                "task_type": "spend_summarization",
                "example_count": len(examples),
                "note": "Fact-grounded: every number in the narrative was computed via "
                        "real SQL aggregation, not guessed. Only the phrasing is templated.",
            }
        else:
            examples, stats = run_stage_b(clean_df, task_type)

        shaped_outputs[task_type] = examples
        manifest.set_shaping(task_type, stats)

    _progress("Done", 1.0)
    return {
        "mapping_report": mapping_report,
        "quarantined_columns": quarantined_columns,
        "clean_df": clean_df,
        "cleaning_stats": cleaning_stats,
        "split_stats": split_stats,
        "shaped_outputs": shaped_outputs,
        "manifest": manifest,
        "fatal_error": None,
    }
